image: golang:1.12

cache:
  paths:
    - /apt-cache
    - /go/src/github.com
    - /go/src/golang.org
    - /go/src/google.golang.org
    - /go/src/gopkg.in

stages:
  - test
  - build

before_script:
  - go mod vendor
  - apt-get install -y
      fuse3
      libfuse3-dev
  - apt-get clean

unit_tests:
  stage: test
  script:
    - make test

race_detector:
  stage: test
  script:
    - make race
